name: Azaan Notification Scheduler

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "GitHub Action Working!"
